// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zijwvzfkanqirtyzwzzt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inppand2emZrYW5xaXJ0eXp3enp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MDA3OTMsImV4cCI6MjA1ODM3Njc5M30.s5YC9wguLgNwIHSkeyl4yOiS2uJfX6TavlRNdjoF1Uo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);